jobs:
- job: linux
  container: unoplatform/wasm-build:3.0

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    DotnetRuntimePath: /usr/share/dotnet

  steps:
  - checkout: self
    clean: true

  - template: build/canary-updater.yml
  - template: build/gitversion.yml

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 5.0.101

  - script: |
      cd $(build.sourcesdirectory)
      dotnet msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/Uno.Playground.WASM/Uno.Playground.WASM.csproj  "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" /bl:$(build.artifactstagingdirectory)/linux.binlog

    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)
    displayName: 'Build Playground'

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Uno.Playground.WASM/bin/Release/net5.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container
